Repository cse110-sp21-group8/cse110-sp21-group8, pull requests merged in 2021-05, with the labels that each got.

#9 justify guidelines
  .gitignore
  specs/adrs/050521-Guidelines.md
Labels: documentation

#11 Repo/feature/test workflow
  .eslintrc.json
  .github/workflows/integrate.yml
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc
  jsdoc.json
  package.json
  source/test
  src/index.js
  yarn.lock
Labels: enhancement, feature, repo

#13 add jest framework for testing
  .eslintrc.json
  .github/workflows/generate-doc.yml
  .github/workflows/lint-prettify.yml
  .github/workflows/test.yml
  .husky/.gitignore
  .husky/pre-commit
  package.json
  src/js/greet.js
  src/test/greet.test.js
  yarn.lock
Labels: feature, repo, testing

#14 Front end: Finished daily logs and custom logs (html and css)
  css/custom.css
  css/daily.css
  css/future.css
  css/index.css
  css/monthly.css
  custom.html
  daily.html
  future.html
  index.html
  monthly.html
Labels: frontend

#21 Repo/feature/auto commit prettier
  .github/workflows/lint-prettify.yml
  .github/workflows/test.yml
Labels: enhancement, repo

#22 Repo/modify/add jsdocs directory
  .github/workflows/generate-doc.yml
  .gitignore
  package-lock.json
Labels: enhancement, feature, repo

#26 move index into root directory and change hrefs
  .github/workflows/deploy.yml
  index.html
  src/html/custom.html
  src/html/daily.html
  src/html/future.html
  src/html/monthly.html
Labels: enhancement, repo

#27 use draw.io to update ci/cd diagram
  admin/cipipeline/phase1.drawio
  admin/cipipeline/phase1.png
Labels: documentation, enhancement, repo
